### ISSUE TITLE
Icons show as rectangle with "X" in the middle?

### ISSUE THREAD

**Issue by mfromin** [drewbkoch/Brackets-File-Icons#25]
I tried installing this plugin today and I get a strange UI outcome:

![screen shot 2015-04-28 at 1 23 45 pm](https://cloud.githubusercontent.com/assets/2193139/7378324/d69d6b02-eda9-11e4-9d37-70779594096e.png)

...any idea what could cause this?  (On a Mac if that matters)

**Comment by AdriVanHoudt** [comment]
press f12 to open up dev tools and see if the console prints any warning. Also are you on 0.13?

**Comment by mfromin** [comment]
I am on Brackets 1.3 - yes.  When I open the dev tools I see some deprecation warnings for another extension (beautify) and I see this:

FileUtils.getSmartFileExtension() has been deprecated. Please use LanguageManager.getCompoundFileExtension() instead.
    at Object.getSmartFileExtension (/file/FileUtils.js:358:28)
    at provider (file:///Users/mfromin/Library/Application%20Support/Brackets/extensions/user/drewkoch.icons/main.js:145:23)
    at eval (/project/FileTreeView.js:267:38)
    at eval (/thirdparty/immutable.js:463:26)
    at eachFn (/thirdparty/immutable.js:1921:11)
    at iterateVNode (/thirdparty/immutable.js:2065:44)
    at Vector.__iterate (/thirdparty/immutable.js:1933:121)
    at IndexedSequence.mappedSequence.__iterateUncached (/thirdparty/immutable.js:462:23)
    at IndexedSequence.__iterate (/thirdparty/immutable.js:636:19)

**Comment by AdriVanHoudt** [comment]
hmm works for me(on windows), the warning should be easily resolved(i might do a pr tomorrow).
As for your error. try disabling extensions and see if that works

**Comment by mfromin** [comment]
Disabling extensions indeed removes the error but also stops the extension from loading so I get no icons.

Oddly I can install the Brackets Icons extension and those icons do indeed show up for me.

--Michael

**Comment by AdriVanHoudt** [comment]
ok try enabling 1 at a time to see what breaks it

**Comment by mfromin** [comment]
Culprit found:  Themes For Brackets (https://github.com/Jacse/themes-for-brackets) is causing this.  Unfortunately the color scheme I use all day is part of that package so I really can’t uninstall that extension. 

--Michael

**Comment by AdriVanHoudt** [comment]
hmm no idea why that would interfere

**Comment by AdriVanHoudt** [comment]
I added a PR to fix the warning ;)

**Comment by mfromin** [comment]
Thanks.  I asked the author of the other extension to look at why your icons get messed up when his extension is installed. 

--Michael

**Comment by AdriVanHoudt** [comment]
maybe @drewbkoch knows :D

**Comment by drewbkoch** [comment]
It must have been due to a recent update from Themes for Brackets. What
version of Themes are you on? For me, there is no conflict with version
2.0.10
ᐧ

On Tue, Apr 28, 2015 at 1:52 PM, AdriVanHoudt notifications@github.com
wrote:

> maybe @drewbkoch https://github.com/drewbkoch knows :D
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/drewbkoch/Brackets-File-Icons/issues/25#issuecomment-97203602
> .

## 

## 

Drew Koch
drewkoch.com

**Comment by mfromin** [comment]
I am on 2.0.11

--Michael

**Comment by AdriVanHoudt** [comment]
It's weird since the only css class file-icons uses is `.fileicon` and themes doesn't use it
