### ISSUE TITLE
FileUtils.getSmartFileExtension() has been deprecated. warning

### ISSUE THREAD

**Issue by senhongo** [drewbkoch/Brackets-File-Icons#27]
Have been getting this error for some time now.
The icons still display fine though.
Using release 1.3 on OS X 10.10.3

```
FileUtils.getSmartFileExtension() has been deprecated. Please use LanguageManager.getCompoundFileExtension() instead.
    at Object.getSmartFileExtension (/file/FileUtils.js:358:28)
    at provider (file:///Users/UserName/Library/Application%20Support/Brackets/extensions/user/drewkoch.icons/main.js:145:23)
    at eval (/project/WorkingSetView.js:1135:24)
    at Array.forEach (native)
    at WorkingSetView._createNewListItem (/project/WorkingSetView.js:1134:24)
    at eval (/project/WorkingSetView.js:1177:18)
    at Array.forEach (native)
    at WorkingSetView._rebuildViewList (/project/WorkingSetView.js:1176:18)
    at WorkingSetView._handleFileListAdded (/project/WorkingSetView.js:1244:18)
```

**Comment by AdriVanHoudt** [comment]
there is an open PR for this https://github.com/drewbkoch/Brackets-File-Icons/pull/26
@drewbkoch ?
